package cotesmodulos;


/**
* cotesmodulos/cotesinterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cotesfacturas.idl
* lunes 29 de abril de 2019 01:34:08 AM BOT
*/

public interface cotesinterfaceOperations 
{
  String facturaspendientes (int numero);
  void pagar (int idfactura);
} // interface cotesinterfaceOperations
