package cotesmodulos;

/**
* cotesmodulos/cotesinterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cotesfacturas.idl
* lunes 29 de abril de 2019 01:34:08 AM BOT
*/

public final class cotesinterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public cotesmodulos.cotesinterface value = null;

  public cotesinterfaceHolder ()
  {
  }

  public cotesinterfaceHolder (cotesmodulos.cotesinterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cotesmodulos.cotesinterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        cotesmodulos.cotesinterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cotesmodulos.cotesinterfaceHelper.type ();
  }

}
