package cotesmodulos;


/**
* cotesmodulos/cotesinterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cotesfacturas.idl
* lunes 29 de abril de 2019 01:34:08 AM BOT
*/

public interface cotesinterface extends cotesinterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface cotesinterface
