package cotesmodulos;


/**
* cotesmodulos/cotesinterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cotesfacturas.idl
* lunes 29 de abril de 2019 01:34:08 AM BOT
*/

abstract public class cotesinterfaceHelper
{
  private static String  _id = "IDL:cotesmodulos/cotesinterface:1.0";

  public static void insert (org.omg.CORBA.Any a, cotesmodulos.cotesinterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cotesmodulos.cotesinterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (cotesmodulos.cotesinterfaceHelper.id (), "cotesinterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cotesmodulos.cotesinterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_cotesinterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cotesmodulos.cotesinterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static cotesmodulos.cotesinterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cotesmodulos.cotesinterface)
      return (cotesmodulos.cotesinterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
            cotesmodulos._cotesinterfaceStub stub = new cotesmodulos._cotesinterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static cotesmodulos.cotesinterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cotesmodulos.cotesinterface)
      return (cotesmodulos.cotesinterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
            cotesmodulos._cotesinterfaceStub stub = new cotesmodulos._cotesinterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
